### ISSUE TITLE
Cloud Monitoring Exporter Example - TypeError

### ISSUE THREAD

**Issue by andrewmackett** [GoogleCloudPlatform/opentelemetry-operations-python#189]
I'm looking to get started with the Cloud Monitoring Exporter and have followed the [example documentation](https://google-cloud-opentelemetry.readthedocs.io/en/latest/examples/cloud_monitoring/README.html).
When run, it produces `TypeError: Descriptors cannot not be created directly.`.

```
python -V

Python 3.9.9
```

```
pip freeze

cachetools==5.1.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
google-api-core==2.8.0
google-auth==2.6.6
google-cloud-monitoring==1.1.1
googleapis-common-protos==1.56.1
grpcio==1.46.3
grpcio-status==1.46.3
idna==3.3
opentelemetry-api==1.10a0
opentelemetry-exporter-gcp-monitoring==1.3.0a0
opentelemetry-sdk==1.10a0
protobuf==4.21.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.27.1
rsa==4.8
six==1.16.0
urllib3==1.26.9
```

```
python main.py 
Traceback (most recent call last):
  File "/Users/andrewmackett/otel-metrics/main.py", line 19, in <module>
    from opentelemetry.exporter.cloud_monitoring import (
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/opentelemetry/exporter/cloud_monitoring/__init__.py", line 24, in <module>
    from google.cloud.monitoring_v3 import MetricServiceClient
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/google/cloud/monitoring_v3/__init__.py", line 22, in <module>
    from google.cloud.monitoring_v3 import types
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/google/cloud/monitoring_v3/types.py", line 27, in <module>
    from google.cloud.monitoring_v3.proto import alert_pb2
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/google/cloud/monitoring_v3/proto/alert_pb2.py", line 16, in <module>
    from google.cloud.monitoring_v3.proto import (
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/google/cloud/monitoring_v3/proto/common_pb2.py", line 41, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Users/andrewmackett/.pyenv/versions/otel-metrics/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by aabmass** [comment]
`google-cloud-monitoring` seems to have fixed this https://github.com/googleapis/python-monitoring/pull/448. It was released in 1.1.2. Lmk if that doesn't fix your issue :)
