### ISSUE TITLE
Deadline Exceeded when using CloudTraceSpanExporter in celery with gevent pool

### ISSUE THREAD

**Issue by Pitirus** [GoogleCloudPlatform/opentelemetry-operations-python#336]
Hi,
I'm using celery with a gevent pool. Looks like CloudTraceSpanExporter doesn't work correctly with gevent.

# Stack trace

```
Hello from task_test_otel
 
_Span(name="my_test", context=SpanContext(trace_id=0xa77a2c681e94f7b7a94558b313a21196, span_id=0x8e9a20b7daab8335, trace_flags=0x01, trace_state=[], is_remote=False))
Error while writing to Cloud Trace
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
       status = StatusCode.DEADLINE_EXCEEDED
       details = "Deadline Exceeded"
       debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-28T12:01:32.624626752+00:00", grpc_status:4, grpc_message:"Deadline Exceeded"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 81, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/opentelemetry/exporter/cloud_trace/__init__.py", line 197, in export
    self.client.batch_write_spans(
  File "/usr/lib/python3.11/site-packages/google/cloud/trace_v2/services/trace_service/client.py", line 774, in batch_write_spans
    rpc(
  File "/usr/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/usr/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 221, in _retry_error_helper
    raise final_exc from source_exc
google.api_core.exceptions.RetryError: Timeout of 120.0s exceeded, last exception: 504 Deadline Exceeded
Substantial drift from celery@fbb3ec6362fb may mean clocks are out of sync.  Current drift is 118 seconds.  [orig: 2024-06-28 12:01:32.640659 recv: 2024-06-28 11:59:34.167493]
```

# How to reproduce

command to run celery
```
celery -A my_app worker --pool gevent --concurrency 5
```

celery.py
```python
from gevent import monkey

# Otherwise CloudTraceSpanExporter blocks the main thread.
# CloudTraceSpanExporter fails with timeouts, no matter if this method is used or not.
monkey.patch_all()

import os

import celery.concurrency.gevent
from celery import Celery
from celery import signals
from celery.worker.consumer import Consumer
from opentelemetry import trace
from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
from opentelemetry.instrumentation.celery import CeleryInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_app.settings")
app = Celery("my_app")
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()


# Running otel initialization with other signals causes assertion errors
# https://github.com/open-telemetry/opentelemetry-python/issues/3897
# Running otel with ConsoleSpanExporter works fine when initialized from this signal
@signals.worker_ready.connect(weak=False)
def worker_ready(sender: Consumer | None = None, **kwargs):
    if isinstance(sender.pool, celery.concurrency.gevent.TaskPool):
        resource = Resource.create()
        tracer_provider = TracerProvider(resource=resource)
        processor = BatchSpanProcessor(CloudTraceSpanExporter())
        tracer_provider.add_span_processor(processor)
        trace.set_tracer_provider(tracer_provider)
        CeleryInstrumentor().instrument()
```

tasks.py
```python
from my_app.celery import app
from opentelemetry import trace

tracer = trace.get_tracer(__name__)


@app.task(ignore_results=True)
def task_test_otel():
    with tracer.start_as_current_span("my_test") as t:
        print("Hello from task_test_otel", t)
```

**Comment by aabmass** [comment]
Thanks for the clean bug report and repro. Based on

```
google.api_core.exceptions.RetryError: Timeout of 120.0s exceeded, last exception: 504 Deadline Exceeded
```
and 
```
Substantial drift from celery@fbb3ec6362fb may mean clocks are out of sync.  Current drift is 118 seconds.  [orig: 2024-06-28 12:01:32.640659 recv: 2024-06-28 11:59:34.167493]
```

How do you know it's not actually just exceeding the deadline? The clock drift log seems concerning. I have to admit I'm not too familiar with celery or gevent.

**Comment by aabmass** [comment]
My first feeling is that the issue is with gRPC which is used under the hood. However, you can pass your own `TraceServiceClient` into the exporter https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/cc61f23a5ff2f16f4aa2c38d07e55153828849cc/opentelemetry-exporter-gcp-trace/src/opentelemetry/exporter/cloud_trace/__init__.py#L163

and you can create your client to use HTTP/REST (with requests) with `TraceServiceClient(transport="rest")`. Can you see if that fixes the issue?

**Comment by aabmass** [comment]
I tested this out and it looks like it's just an issue with gevent and gRPC, unrelated to Celery. Forcing REST does fix the issue, otherwise it hangs like you mentioned.

```py
import gevent.monkey

gevent.monkey.patch_all()

from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter

from google.cloud.trace import TraceServiceClient

tp = TracerProvider()
tp.add_span_processor(
    BatchSpanProcessor(
        CloudTraceSpanExporter(client=TraceServiceClient(transport="rest")),
    )
)


for _ in range(10):
    with tp.get_tracer("foo").start_as_current_span("test"):
        pass
```

I'd recommend opening an issue with gRPC if there is isn't an appropriate one already.
